apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: writable-stream-parallel
  description: Parallelize your _write()s
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
