// Generated by CoffeeScript 1.6.1
(function() {
  var Duplex, Readable, Writable;

  Readable = require('stream').Readable;

  Writable = require('./writable');

  Duplex = (function() {

    Duplex.mixin(Writable);

    Duplex.mixin(Readable);

    function Duplex(options) {
      Writable.call(this, options);
      Readable.call(this, options);
    }

    return Duplex;

  })();

  module.exports = Duplex;

}).call(this);
