// Generated by CoffeeScript 1.6.1
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Object.prototype.mixin = function(Klass, exclude) {
    var key, value, _ref;
    if (exclude == null) {
      exclude = [];
    }
    for (key in Klass) {
      value = Klass[key];
      this[key] = value;
    }
    _ref = Klass.prototype;
    for (key in _ref) {
      value = _ref[key];
      if (__indexOf.call(exclude, key) < 0) {
        this.prototype[key] = value;
      }
    }
    return this;
  };

  module.exports = {
    Writable: require("" + __dirname + "/writable"),
    Duplex: require("" + __dirname + "/duplex"),
    Transform: require("" + __dirname + "/transform")
  };

}).call(this);
