// Generated by CoffeeScript 1.6.1
var Duplex, NodeReadable, Writable;

NodeReadable = require('readable-stream');

Writable = require('./writable');

Duplex = (function() {

  Duplex.mixin(Writable);

  Duplex.mixin(NodeReadable);

  function Duplex(options) {
    Writable.call(this, options);
    NodeReadable.call(this, options);
  }

  return Duplex;

})();

module.exports = Duplex;
